"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  Plus,
  Search,
  Pencil,
  Trash2,
  X,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Award,
  Minus,
  ListChecks,
  PenTool,
  BookOpen,
  Calendar as CalendarIcon,
} from "lucide-react";
import {
  getCertificates,
  createCertificate,
  updateCertificate,
  deleteCertificate,
  generateCertificateNumber,
  translateText,
  Certificate,
  CertificateFormData,
} from "@/app/actions/certificate";
import { useConfirmation } from "@/components/providers/modal-provider";
import { useAlert } from "@/hooks/use-alert";
import {
  TableWrapper,
  TableScrollArea,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableEmpty,
  TablePagination,
  TableHeaderContent,
  TableAnalysis,
  TableAnalysisCardProps,
} from "@/components/ui/table";
import PdfSignatureModal, {
  SignatureType,
} from "@/components/ui/pdf-signature-modal";
import Modal from '@/components/ui/modal'

interface CertificateManagerProps {
  initialData?: Certificate[];
}

// Default text templates - matching CI-Generate
const DEFAULT_TEXTS = {
  present_text_idn: "Sertifikat ini dengan bangga diserahkan kepada:",
  present_text_en: "This certificate is proudly presented to:",
  description_text_idn:
    "Sebagai bentuk penghargaan dan pengakuan atas dedikasi, kedisiplinan, serta komitmen tinggi yang ditunjukkan selama menjalankan kegiatan",
  description_text_en:
    "As a form of appreciation and recognition for the dedication, discipline, and strong commitment demonstrated during the",
  completion_text_idn: "menyelesaikan training",
  completion_text_en: "successfully completed the training",
  evaluation_text_idn: "Sangat Baik",
  evaluation_text_en: "Excellent",
};

// Available institutions - matching CI-Generate
const INSTITUTIONS = ["PT. GAGAS ANAGATA NUSANTARA", "ICHIBOT"];

// Note: Certificate number is generated by backend (CI-Generate) to ensure correct sequence

export default function CertificateManager({
  initialData = [],
}: CertificateManagerProps) {
  const { showConfirmation } = useConfirmation();
  const { showAlert } = useAlert();

  // State
  const [certificates, setCertificates] = useState<Certificate[]>(initialData);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);

  // Refs for stable function references
  const fetchCertificatesRef = useRef<
    ((page?: number, searchQuery?: string) => Promise<void>) | null
  >(null);

  // Modal state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCertificate, setEditingCertificate] =
    useState<Certificate | null>(null);
  const [saving, setSaving] = useState(false);

  // PDF Download Modal state
  const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);
  const [selectedCertificateForPdf, setSelectedCertificateForPdf] =
    useState<Certificate | null>(null);

  // Refs for auto-translate debouncing
  const translateTimeouts = useRef<Record<string, NodeJS.Timeout>>({});

  // Form state - all required fields with CI-Generate defaults
  const [formData, setFormData] = useState<CertificateFormData>({
    certificate_number: "",
    recipient_name: "",
    instansi: "",
    present_text_idn: DEFAULT_TEXTS.present_text_idn,
    present_text_en: DEFAULT_TEXTS.present_text_en,
    description_text_idn: DEFAULT_TEXTS.description_text_idn,
    description_text_en: DEFAULT_TEXTS.description_text_en,
    activity_text_idn: "",
    activity_text_en: "",
    completion_text_idn: DEFAULT_TEXTS.completion_text_idn,
    completion_text_en: DEFAULT_TEXTS.completion_text_en,
    evaluation_text_idn: DEFAULT_TEXTS.evaluation_text_idn,
    evaluation_text_en: DEFAULT_TEXTS.evaluation_text_en,
    start_date: "",
    end_date: "",
    signature_name: "",
    materi_judul: "",
    materi: [],
    nilai: [],
  });

  // Fetch certificates
  const fetchCertificates = useCallback(
    async (page = 1, searchQuery = "") => {
      setLoading(true);
      try {
        const result = await getCertificates({
          page,
          per_page: 15,
          search: searchQuery || undefined,
        });

        if (result.success && result.data) {
          const certificatesData = result.data.certificates || [];
          const paginationData = result.data.pagination;

          setCertificates(certificatesData);
          setTotalPages(paginationData?.last_page || 1);
          setTotal(paginationData?.total || 0);
          setCurrentPage(paginationData?.current_page || 1);
        } else {
          showAlert(result.message || "Gagal mengambil data", "error");
        }
      } catch {
        showAlert("Terjadi kesalahan", "error");
      } finally {
        setLoading(false);
      }
    },
    [showAlert],
  );

  // Handle PDF download with format selection
  const handlePdfDownload = async (signatureType: SignatureType) => {
    if (!selectedCertificateForPdf) return;

    // Map signatureType to actual parameters for Certificate API
    let externalUrl = "";
    const pdfUrls = selectedCertificateForPdf.pdf_urls;

    if (!pdfUrls) {
      alert("URL PDF tidak ditemukan.");
      return;
    }

    switch (signatureType) {
      case "cert_ichibot":
        externalUrl = pdfUrls.secure_download_ichibot;
        break;
      case "cert_gan":
        externalUrl = pdfUrls.secure_download_gan;
        break;
      case "cert_qr_ichibot":
        externalUrl = `${pdfUrls.secure_download_ichibot.split("?")[0]}?logo=ichibot&qr_code=1`;
        break;
      case "cert_qr_gan":
        externalUrl = `${pdfUrls.secure_download_gan.split("?")[0]}?logo=gan&qr_code=1`;
        break;
      default:
        // Fallback to ICHIBOT
        externalUrl = pdfUrls.secure_download_ichibot;
    }

    // Use local API proxy to avoid CORS
    const proxyUrl = `/api/download-pdf?url=${encodeURIComponent(externalUrl)}`;

    try {
      const response = await fetch(proxyUrl);

      if (!response.ok) {
        const errorData = await response.json();
        alert(
          `Gagal mengunduh: ${errorData.error}\n${errorData.details || ""}`,
        );
        return;
      }

      const contentType = response.headers.get("content-type");
      if (!contentType?.includes("application/pdf")) {
        alert("Server tidak mengembalikan file PDF. Silakan coba lagi nanti.");
        return;
      }

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      const safeNumber = selectedCertificateForPdf.certificate_number.replace(
        /[/\\?%*:|"<>]/g,
        "-",
      );
      link.download = `Sertifikat-${safeNumber}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (error) {
      console.error("Failed to download PDF:", error);
      alert("Terjadi kesalahan teknis saat mengunduh PDF.");
    }
  };

  // Keep ref updated
  fetchCertificatesRef.current = fetchCertificates;

  // Initial load - only run once on mount
  useEffect(() => {
    if (initialData.length === 0) {
      fetchCertificates();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Search with debounce - skip first render
  const isFirstRender = useRef(true);
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }
    const timer = setTimeout(() => {
      fetchCertificatesRef.current?.(1, search);
    }, 500);
    return () => clearTimeout(timer);
  }, [search]);

  // Lock body scroll when modal is open
  useEffect(() => {
    if (isModalOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isModalOpen]);

  // Reset form - certificate_number left empty so backend generates it correctly
  const resetForm = () => {
    setFormData({
      certificate_number: "", // Leave empty, backend will generate the correct sequence
      recipient_name: "",
      instansi: "",
      present_text_idn: DEFAULT_TEXTS.present_text_idn,
      present_text_en: DEFAULT_TEXTS.present_text_en,
      description_text_idn: DEFAULT_TEXTS.description_text_idn,
      description_text_en: DEFAULT_TEXTS.description_text_en,
      activity_text_idn: "",
      activity_text_en: "",
      completion_text_idn: DEFAULT_TEXTS.completion_text_idn,
      completion_text_en: DEFAULT_TEXTS.completion_text_en,
      evaluation_text_idn: DEFAULT_TEXTS.evaluation_text_idn,
      evaluation_text_en: DEFAULT_TEXTS.evaluation_text_en,
      start_date: "",
      end_date: "",
      signature_name: "",
      materi_judul: "",
      materi: [],
      nilai: [],
    });
  };

  // Handle Indonesian field change with auto-translate to English
  // Fields that should be translated: present_text, description_text, activity_text, completion_text, evaluation_text
  const handleIdnChange = (
    idnField: keyof CertificateFormData,
    enField: keyof CertificateFormData,
    value: string,
    shouldTranslate: boolean = true,
  ) => {
    // Update Indonesian field immediately
    setFormData((prev) => ({
      ...prev,
      [idnField]: value,
    }));

    // If should translate, debounce the translation
    if (shouldTranslate && value.trim()) {
      // Clear existing timeout for this field
      if (translateTimeouts.current[idnField as string]) {
        clearTimeout(translateTimeouts.current[idnField as string]);
      }

      // Set new timeout for translation
      translateTimeouts.current[idnField as string] = setTimeout(async () => {
        try {
          const translated = await translateText(value);
          setFormData((prev) => ({
            ...prev,
            [enField]: translated,
          }));
        } catch (error) {
          console.error("Translation failed:", error);
        }
      }, 500); // 500ms debounce
    } else if (!value.trim()) {
      // Clear English field if Indonesian is empty
      setFormData((prev) => ({
        ...prev,
        [enField]: "",
      }));
    }
  };

  // Open add modal - fetch next certificate number from API
  const openAddModal = async () => {
    setEditingCertificate(null);
    resetForm();
    setIsModalOpen(true);

    // Fetch next certificate number from API
    try {
      const nextNumber = await generateCertificateNumber();
      setFormData((prev) => ({
        ...prev,
        certificate_number: nextNumber,
      }));
    } catch (error) {
      console.error("Failed to fetch certificate number:", error);
    }
  };

  // Open edit modal
  const openEditModal = (certificate: Certificate) => {
    setEditingCertificate(certificate);
    setFormData({
      certificate_number: certificate.certificate_number,
      recipient_name: certificate.recipient_name,
      instansi: certificate.instansi || "ICHIBOT",
      present_text_idn:
        certificate.present_text_idn || DEFAULT_TEXTS.present_text_idn,
      present_text_en:
        certificate.present_text_eng || DEFAULT_TEXTS.present_text_en,
      description_text_idn:
        certificate.description_text_idn || DEFAULT_TEXTS.description_text_idn,
      description_text_en:
        certificate.description_text_eng || DEFAULT_TEXTS.description_text_en,
      activity_text_idn: certificate.activity_text_idn || "",
      activity_text_en: certificate.activity_text_eng || "",
      completion_text_idn:
        certificate.completion_text_idn || DEFAULT_TEXTS.completion_text_idn,
      completion_text_en:
        certificate.completion_text_eng || DEFAULT_TEXTS.completion_text_en,
      evaluation_text_idn:
        certificate.evaluation_text_idn || DEFAULT_TEXTS.evaluation_text_idn,
      evaluation_text_en:
        certificate.evaluation_text_eng || DEFAULT_TEXTS.evaluation_text_en,
      start_date: certificate.start_date?.split("T")[0] || "",
      end_date: certificate.end_date?.split("T")[0] || "",
      signature_name: certificate.signature_name || "Eko Rudiawan, S.T., M.Eng",
      materi_judul: certificate.materi_judul || "",
      materi: certificate.materi || [],
      nilai: certificate.materi_nilai || [],
    });
    setIsModalOpen(true);
  };

  // Handle submit
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.recipient_name.trim()) {
      showAlert("Nama penerima harus diisi", "error");
      return;
    }

    if (!formData.activity_text_idn.trim()) {
      showAlert("Kegiatan (Indonesia) harus diisi", "error");
      return;
    }

    if (!formData.activity_text_en.trim()) {
      showAlert("Kegiatan (English) harus diisi", "error");
      return;
    }

    if (!formData.instansi) {
      showAlert("Instansi harus dipilih", "error");
      return;
    }

    setSaving(true);
    try {
      const result = editingCertificate
        ? await updateCertificate(editingCertificate.id, formData)
        : await createCertificate(formData);

      if (result.success) {
        showAlert(result.message || "Berhasil!", "success");
        setIsModalOpen(false);
        fetchCertificates(currentPage, search);
      } else {
        showAlert(result.message || "Gagal menyimpan", "error");
      }
    } catch {
      showAlert("Terjadi kesalahan", "error");
    } finally {
      setSaving(false);
    }
  };

  // Handle delete
  const handleDelete = (certificate: Certificate) => {
    showConfirmation({
      title: "Hapus Sertifikat",
      message: `Apakah Anda yakin ingin menghapus sertifikat ${certificate.certificate_number}?`,
      type: "confirm",
      action: async () => {
        try {
          const result = await deleteCertificate(certificate.id);
          if (result.success) {
            showAlert("Sertifikat berhasil dihapus", "success");
            fetchCertificates(currentPage, search);
          } else {
            showAlert(result.message || "Gagal menghapus", "error");
          }
        } catch {
          showAlert("Terjadi kesalahan", "error");
        }
      },
    });
  };

  // Add materi
  const addMateri = () => {
    setFormData({
      ...formData,
      materi: [...(formData.materi || []), ""],
      nilai: [...(formData.nilai || []), 0],
    });
  };

  // Remove last materi
  const removeMateri = () => {
    if ((formData.materi?.length || 0) > 0) {
      setFormData({
        ...formData,
        materi: formData.materi?.slice(0, -1) || [],
        nilai: formData.nilai?.slice(0, -1) || [],
      });
    }
  };

  // Update materi name
  const updateMateriName = (index: number, value: string) => {
    const newMateri = [...(formData.materi || [])];
    newMateri[index] = value;
    setFormData({ ...formData, materi: newMateri });
  };

  // Update nilai
  const updateNilai = (index: number, value: number | string) => {
    const newNilai = [...(formData.nilai || [])];
    newNilai[index] = value;
    setFormData({ ...formData, nilai: newNilai });
  };

  // Analysis Cards mapping
  const certsThisMonth = certificates.filter((cert) => {
    const d = new Date(cert.start_date);
    const now = new Date();
    return (
      d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
    );
  }).length;

  const analysisCards: TableAnalysisCardProps[] = [
    {
      label: "Total Sertifikat",
      value: total,
      icon: <Award className="w-4 h-4" />,
      description: "Total keseluruhan sertifikat",
    },
    {
      label: "Bulan Ini",
      value: certsThisMonth,
      icon: <CalendarIcon className="w-4 h-4" />,
      description: "Sertifikat diterbitkan bulan ini",
    },
    {
      label: "Top Penerima",
      value: certificates[0]?.recipient_name || "-",
      icon: <div className="text-[10px] font-bold text-primary">TOP</div>,
      description: "Penerima terbaru",
    },
    {
      label: "Verifikasi QR",
      value: "Aktif",
      icon: (
        <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
      ),
      description: "Sistem verifikasi aktif",
    },
  ];

  return (
    <div className="space-y-6">
      <TableAnalysis cards={analysisCards} />

      <TableWrapper>
        <TableHeaderContent
          title="Sertifikat"
          description="Kelola sertifikat pelatihan, kompetensi, dan penghargaan."
          icon={<Award className="w-5 h-5 font-bold text-emerald-600" />}
          actions={
            <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
              <div className="relative w-full sm:w-64">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="Cari sertifikat..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 bg-background border border-border rounded-lg text-foreground text-sm focus:border-emerald-500 outline-none transition-all shadow-sm"
                />
              </div>
              <button
                onClick={openAddModal}
                className="px-4 h-9 bg-emerald-500 text-white rounded-lg text-sm font-bold transition-all hover:bg-emerald-600 shadow-sm flex items-center gap-2 whitespace-nowrap"
              >
                <Plus className="w-4 h-4" />
                Tambah Sertifikat
              </button>
            </div>
          }
        />
        <TableScrollArea>
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>No. Sertifikat</TableHead>
                  <TableHead>Nama Penerima</TableHead>
                  <TableHead>Aktivitas</TableHead>
                  <TableHead>Materi & Nilai</TableHead>
                  <TableHead>Periode</TableHead>
                  <TableHead>PDF</TableHead>
                  <TableHead align="right">Aksi</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {certificates.map((certificate) => (
                  <TableRow key={certificate.id}>
                    <TableCell>
                      <span className="font-mono text-sm font-medium text-emerald-600">
                        {certificate.certificate_number}
                      </span>
                    </TableCell>
                    <TableCell>
                      <div>
                        <p className="font-medium">
                          {certificate.recipient_name}
                        </p>
                        {certificate.instansi && (
                          <p className="text-xs text-muted-foreground">
                            {certificate.instansi}
                          </p>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <p className="font-medium line-clamp-2 max-w-xs">
                        {certificate.activity_text_idn}
                      </p>
                    </TableCell>
                    <TableCell>
                      {certificate.materi && certificate.materi.length > 0 ? (
                        <div className="space-y-1 max-w-sm">
                          {certificate.materi.map((m, idx) => (
                            <div
                              key={idx}
                              className="flex items-center gap-2 text-[11px]"
                            >
                              <span className="w-5 h-5 bg-blue-50 text-blue-600 rounded-md flex items-center justify-center font-semibold text-[10px] shrink-0">
                                {idx + 1}
                              </span>
                              <span className="text-gray-700 truncate flex-1">
                                {m}
                              </span>
                              <span className="ml-auto px-2 py-0.5 bg-emerald-50 text-emerald-700 rounded-md font-semibold text-[10px] shrink-0">
                                {certificate.materi_nilai?.[idx] ?? "-"}
                              </span>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <span className="text-xs text-muted-foreground/50 italic">
                          -
                        </span>
                      )}
                    </TableCell>
                    <TableCell className="whitespace-nowrap">
                      <div className="text-sm">
                        <p>
                          {new Date(certificate.start_date).toLocaleDateString(
                            "id-ID",
                            {
                              day: "numeric",
                              month: "short",
                              year: "numeric",
                            },
                          )}
                        </p>
                        <p className="text-muted-foreground">
                          s/d{" "}
                          {new Date(certificate.end_date).toLocaleDateString(
                            "id-ID",
                            {
                              day: "numeric",
                              month: "short",
                              year: "numeric",
                            },
                          )}
                        </p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <button
                        onClick={() => {
                          setSelectedCertificateForPdf(certificate);
                          setIsPdfModalOpen(true);
                        }}
                        className="p-1.5 bg-blue-500/10 text-blue-600 rounded-lg hover:bg-blue-500/20 transition-colors inline-flex"
                        title="Unduh PDF"
                      >
                        <Award className="w-4 h-4" />
                      </button>
                    </TableCell>
                    <TableCell align="right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => openEditModal(certificate)}
                          className="p-2 hover:bg-blue-50 text-blue-600 rounded-lg transition-colors"
                          title="Edit"
                        >
                          <Pencil className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(certificate)}
                          className="p-2 hover:bg-red-50 text-red-600 rounded-lg transition-colors"
                          title="Hapus"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
                {certificates.length === 0 && (
                  <TableEmpty
                    colSpan={7}
                    icon={<Award className="w-12 h-12 opacity-20" />}
                  />
                )}
              </TableBody>
              {certificates.length > 0 && (
                <TableFooter>
                  <TableRow hoverable={false}>
                    <TableCell colSpan={7} className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Total Sertifikat:</span>
                        <span className="text-sm font-bold text-primary">{certificates.length} Sertifikat</span>
                      </div>
                    </TableCell>
                  </TableRow>
                </TableFooter>
              )}
            </Table>
          )}
        </TableScrollArea>


        {/* Mobile/Tablet Card View - Premium List */}
        <div className="md:hidden space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <>
              {certificates.map((cert) => (
                <div
                  key={cert.id}
                  className="bg-card border border-border rounded-xl p-5 space-y-4 shadow-sm"
                >
                  <div className="flex justify-between items-start">
                    <div className="space-y-1">
                      <span className="font-mono text-sm font-bold text-emerald-600 uppercase tracking-tight">
                        {cert.certificate_number}
                      </span>
                      <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
                        {cert.instansi || "Ichibot"}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <button
                        onClick={() => openEditModal(cert)}
                        className="p-2 bg-blue-500/10 text-blue-600 rounded-lg"
                      >
                        <Pencil className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(cert)}
                        className="p-2 bg-red-500/10 text-red-600 rounded-lg"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <div>
                    <h4 className="font-bold text-sm">{cert.recipient_name}</h4>
                    <p className="text-xs text-muted-foreground line-clamp-2 mt-1 italic">
                      {cert.activity_text_idn}
                    </p>
                  </div>

                  {cert.materi && cert.materi.length > 0 && (
                    <div className="p-3 bg-muted/30 rounded-lg space-y-2">
                      <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">
                        Materi & Nilai
                      </p>
                      <div className="grid grid-cols-1 gap-1">
                        {cert.materi.slice(0, 3).map((m, idx) => (
                          <div
                            key={idx}
                            className="flex justify-between items-center text-[10px]"
                          >
                            <span className="text-gray-600 truncate mr-2">
                              {m}
                            </span>
                            <span className="font-bold text-emerald-600">
                              {cert.materi_nilai?.[idx] || "-"}
                            </span>
                          </div>
                        ))}
                        {cert.materi.length > 3 && (
                          <p className="text-[8px] text-muted-foreground italic text-center pt-1">
                            +{cert.materi.length - 3} more items
                          </p>
                        )}
                      </div>
                    </div>
                  )}

                  <div className="pt-3 border-t border-border flex justify-between items-center">
                    <div className="text-[10px] text-muted-foreground font-medium">
                      {new Date(cert.start_date).toLocaleDateString("id-ID", {
                        day: "numeric",
                        month: "short",
                      })}{" "}
                      -{" "}
                      {new Date(cert.end_date).toLocaleDateString("id-ID", {
                        day: "numeric",
                        month: "short",
                        year: "numeric",
                      })}
                    </div>
                    <button
                      onClick={() => {
                        setSelectedCertificateForPdf(cert);
                        setIsPdfModalOpen(true);
                      }}
                      className="px-3 py-1.5 bg-emerald-500 text-white text-[10px] font-bold rounded-lg uppercase tracking-wider"
                    >
                      Download PDF
                    </button>
                  </div>
                </div>
              ))}
              {certificates.length === 0 && (
                <div className="py-12 text-center text-muted-foreground bg-muted/20 rounded-xl border border-dashed border-border">
                  No certificates found
                </div>
              )}
            </>
          )}
        </div>

        <TablePagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={(page) => fetchCertificates(page, search)}
          totalCount={total}
        />
      </TableWrapper>


      {/* Modal */}
      {isModalOpen && (
        <Modal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title={
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center">
                <Award className="w-5 h-5 text-emerald-600" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-emerald-700">
                  {editingCertificate
                    ? "Edit Sertifikat"
                    : "Buat Sertifikat Baru"}
                </h2>
                <p className="text-sm font-normal text-emerald-600">
                  {editingCertificate
                    ? "Perbarui data sertifikat"
                    : "Lengkapi form berikut"}
                </p>
              </div>
            </div>
          }
          maxWidth="full"
          className="max-w-6xl"
        >
          {/* Modal Body */}
          <form
            onSubmit={handleSubmit}
            className="flex flex-col flex-1"
          >
            <div className="p-6 overflow-y-auto overscroll-contain flex-1 space-y-6">
              {/* Main Content - Two Column Layout */}
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="grid grid-cols-1 lg:grid-cols-2">
                  {/* Indonesian Column */}
                  <div className="p-6 border-b lg:border-b-0 lg:border-r border-gray-100">
                    {/* Language Header */}
                    <div className="flex items-center gap-3 mb-6 pb-4 border-b border-gray-100">
                      <div className="w-8 h-8 rounded-lg overflow-hidden shadow-sm">
                        <img
                          src="https://flagcdn.com/w40/id.png"
                          alt="Indonesia"
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h3 className="font-semibold text-gray-900 text-sm uppercase tracking-wider">
                          Indonesia
                        </h3>
                        <p className="text-[10px] text-gray-400">
                          Bahasa Indonesia
                        </p>
                      </div>
                    </div>

                    <div className="space-y-5">
                      {/* Nomor Sertifikat */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Nomor Sertifikat{" "}
                          <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.certificate_number || ""}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              certificate_number: e.target.value,
                            })
                          }
                          placeholder="Otomatis jika kosong"
                          className="w-full bg-white border-2 border-emerald-400 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-emerald-400 placeholder:italic focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Teks Pembuka */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Teks Pembuka <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.present_text_idn}
                          onChange={(e) =>
                            handleIdnChange(
                              "present_text_idn",
                              "present_text_en",
                              e.target.value,
                            )
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Nama Penerima */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Nama Penerima{" "}
                          <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.recipient_name}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              recipient_name: e.target.value,
                            })
                          }
                          placeholder="Masukkan nama lengkap penerima"
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Deskripsi */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Deskripsi <span className="text-red-500">*</span>
                        </label>
                        <textarea
                          value={formData.description_text_idn}
                          onChange={(e) =>
                            handleIdnChange(
                              "description_text_idn",
                              "description_text_en",
                              e.target.value,
                            )
                          }
                          rows={2}
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none resize-none"
                        />
                      </div>

                      {/* Kegiatan */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Kegiatan <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.activity_text_idn}
                          onChange={(e) =>
                            handleIdnChange(
                              "activity_text_idn",
                              "activity_text_en",
                              e.target.value,
                            )
                          }
                          placeholder="Contoh: Training of Trainer Basic IoT"
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Instansi */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Instansi <span className="text-red-500">*</span>
                        </label>
                        <select
                          value={formData.instansi}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              instansi: e.target.value,
                            })
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        >
                          <option value="">Pilih Instansi</option>
                          {INSTITUTIONS.map((inst) => (
                            <option key={inst} value={inst}>
                              {inst}
                            </option>
                          ))}
                        </select>
                      </div>

                      {/* Teks Tindakan */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Teks Tindakan{" "}
                          <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.completion_text_idn}
                          onChange={(e) =>
                            handleIdnChange(
                              "completion_text_idn",
                              "completion_text_en",
                              e.target.value,
                            )
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Evaluasi Akhir */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Evaluasi Akhir{" "}
                          <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.evaluation_text_idn}
                          onChange={(e) =>
                            handleIdnChange(
                              "evaluation_text_idn",
                              "evaluation_text_en",
                              e.target.value,
                            )
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Periode Pelaksanaan */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Periode Pelaksanaan{" "}
                          <span className="text-red-500">*</span>
                        </label>
                        <div className="grid grid-cols-2 gap-3">
                          <div>
                            <label className="block text-[10px] text-gray-400 mb-1">
                              Mulai
                            </label>
                            <input
                              type="date"
                              value={formData.start_date}
                              onChange={(e) =>
                                setFormData({
                                  ...formData,
                                  start_date: e.target.value,
                                })
                              }
                              className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] text-gray-400 mb-1">
                              Selesai
                            </label>
                            <input
                              type="date"
                              value={formData.end_date}
                              onChange={(e) =>
                                setFormData({
                                  ...formData,
                                  end_date: e.target.value,
                                })
                              }
                              className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* English Column */}
                  <div className="p-6 bg-gray-50/30">
                    {/* Language Header */}
                    <div className="flex items-center gap-3 mb-6 pb-4 border-b border-gray-200">
                      <div className="w-8 h-8 rounded-lg overflow-hidden shadow-sm">
                        <img
                          src="https://flagcdn.com/w40/gb.png"
                          alt="English"
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h3 className="font-semibold text-gray-900 text-sm uppercase tracking-wider">
                          English
                        </h3>
                        <p className="text-[10px] text-gray-400">
                          Versi Bahasa Inggris
                        </p>
                      </div>
                    </div>

                    <div className="space-y-5">
                      {/* Certificate Number (readonly) */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Certificate Number
                        </label>
                        <input
                          type="text"
                          value={formData.certificate_number || "(Otomatis)"}
                          readOnly
                          className="w-full bg-gray-100 border border-gray-200 rounded-xl px-4 py-3 text-gray-500 font-medium cursor-not-allowed"
                        />
                      </div>

                      {/* Opening Text */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Opening Text
                        </label>
                        <input
                          type="text"
                          value={formData.present_text_en}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              present_text_en: e.target.value,
                            })
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Recipient Name (readonly) */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Recipient Name
                        </label>
                        <input
                          type="text"
                          value={
                            formData.recipient_name ||
                            "(Sama dengan Indonesia)"
                          }
                          readOnly
                          className="w-full bg-gray-100 border border-gray-200 rounded-xl px-4 py-3 text-gray-500 font-medium cursor-not-allowed"
                        />
                      </div>

                      {/* Description */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Description
                        </label>
                        <textarea
                          value={formData.description_text_en}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              description_text_en: e.target.value,
                            })
                          }
                          rows={2}
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none resize-none"
                        />
                      </div>

                      {/* Activity */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Activity
                        </label>
                        <input
                          type="text"
                          value={formData.activity_text_en}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              activity_text_en: e.target.value,
                            })
                          }
                          placeholder="Eg: Training on Basic IoT for WSA Preparation"
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Institution (readonly) */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Institution
                        </label>
                        <input
                          type="text"
                          value={
                            formData.instansi || "(Pilih di kolom Indonesia)"
                          }
                          readOnly
                          className="w-full bg-gray-100 border border-gray-200 rounded-xl px-4 py-3 text-gray-500 font-medium cursor-not-allowed"
                        />
                      </div>

                      {/* Completion Text */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Completion Text
                        </label>
                        <input
                          type="text"
                          value={formData.completion_text_en}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              completion_text_en: e.target.value,
                            })
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Final Evaluation */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Final Evaluation
                        </label>
                        <input
                          type="text"
                          value={formData.evaluation_text_en}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              evaluation_text_en: e.target.value,
                            })
                          }
                          className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                        />
                      </div>

                      {/* Execution Period (readonly) */}
                      <div className="space-y-2">
                        <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                          Execution Period
                        </label>
                        <div className="grid grid-cols-2 gap-3">
                          <div>
                            <label className="block text-[10px] text-gray-400 mb-1">
                              Start
                            </label>
                            <input
                              type="date"
                              value={formData.start_date}
                              readOnly
                              className="w-full bg-gray-100 border border-gray-200 rounded-xl px-4 py-3 text-gray-500 font-medium cursor-not-allowed"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] text-gray-400 mb-1">
                              End
                            </label>
                            <input
                              type="date"
                              value={formData.end_date}
                              readOnly
                              className="w-full bg-gray-100 border border-gray-200 rounded-xl px-4 py-3 text-gray-500 font-medium cursor-not-allowed"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Materi & Nilai Section */}
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-6 py-4 bg-gray-50/50 border-b border-gray-100 flex items-center justify-between">
                  <h2 className="font-semibold text-gray-800 flex items-center gap-2 text-sm uppercase tracking-wider">
                    <ListChecks className="w-4 h-4 text-emerald-600" />
                    Materi & Nilai
                  </h2>

                  {/* Materi Counter */}
                  <div className="flex items-center gap-3">
                    <span className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                      Jumlah Materi
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={removeMateri}
                        disabled={(formData.materi?.length || 0) === 0}
                        className="w-9 h-9 flex items-center justify-center bg-red-50 text-red-600 rounded-xl hover:bg-red-200 transition-colors active:scale-95 border border-red-100 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <Minus className="w-4 h-4" />
                      </button>
                      <input
                        type="text"
                        value={formData.materi?.length || 0}
                        readOnly
                        className="w-14 text-center bg-gray-50 border border-gray-200 rounded-xl py-2 font-semibold text-gray-700 cursor-not-allowed"
                      />
                      <button
                        type="button"
                        onClick={addMateri}
                        className="w-9 h-9 flex items-center justify-center bg-emerald-50 text-emerald-600 rounded-xl hover:bg-emerald-200 transition-colors active:scale-95 border border-emerald-100"
                      >
                        <Plus className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>

                <div className="p-6">
                  {/* Judul Materi */}
                  <div className="mb-6 space-y-2">
                    <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                      Judul Materi
                    </label>
                    <input
                      type="text"
                      value={formData.materi_judul}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          materi_judul: e.target.value,
                        })
                      }
                      placeholder="Contoh: Materi Training IoT"
                      className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                    />
                  </div>

                  {/* Empty State */}
                  {(formData.materi?.length || 0) === 0 && (
                    <div className="py-12 text-center">
                      <div className="inline-flex items-center justify-center w-16 h-16 bg-gray-50 rounded-full mb-4">
                        <BookOpen className="w-8 h-8 text-gray-300" />
                      </div>
                      <p className="text-gray-400 font-semibold mb-1">
                        Belum ada materi
                      </p>
                      <p className="text-sm text-gray-400">
                        Klik tombol{" "}
                        <span className="text-emerald-600 font-semibold">
                          +
                        </span>{" "}
                        di atas untuk menambah materi
                      </p>
                    </div>
                  )}

                  {/* Materi Container */}
                  <div className="space-y-4">
                    {formData.materi?.map((mat, idx) => (
                      <div
                        key={idx}
                        className="bg-gray-50/50 rounded-xl p-5 border border-gray-100"
                      >
                        <div className="flex items-center gap-4">
                          <div className="w-8 h-8 bg-emerald-600 text-white rounded-lg flex items-center justify-center font-semibold text-sm shrink-0">
                            {idx + 1}
                          </div>
                          <div className="flex-1 grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
                            <div className="col-span-3 space-y-1">
                              <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                                Materi {idx + 1}
                              </label>
                              <input
                                type="text"
                                value={mat}
                                onChange={(e) =>
                                  updateMateriName(idx, e.target.value)
                                }
                                placeholder="Deskripsi materi"
                                className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                              />
                            </div>
                            <div className="space-y-1">
                              <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                                Nilai
                              </label>
                              <input
                                type="text"
                                inputMode="numeric"
                                value={formData.nilai?.[idx] ?? ""}
                                onChange={(e) => {
                                  const val = e.target.value;
                                  if (val === "" || /^\d+$/.test(val)) {
                                    updateNilai(idx, val);
                                  }
                                }}
                                placeholder="0-100"
                                className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium text-center focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Tanda Tangan Section */}
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-6 py-4 bg-gray-50/50 border-b border-gray-100">
                  <h2 className="font-semibold text-gray-800 flex items-center gap-2 text-sm uppercase tracking-wider">
                    <PenTool className="w-4 h-4 text-emerald-600" />
                    Tanda Tangan
                  </h2>
                </div>
                <div className="p-6">
                  <div className="space-y-2">
                    <label className="block text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                      Nama Penandatangan{" "}
                      <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.signature_name}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          signature_name: e.target.value,
                        })
                      }
                      placeholder="Contoh: Angga Priyatmoko, S.T., M.Eng."
                      className="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-gray-900 font-medium placeholder:text-gray-300 focus:ring-2 focus:ring-emerald-100 focus:border-emerald-500 transition-all outline-none"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-4 mt-6 border-t border-border shrink-0 bg-emerald-50 flex justify-end gap-4 rounded-b-2xl">
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                className="px-6 py-3 bg-white border border-gray-200 text-gray-600 font-semibold rounded-xl hover:bg-gray-50 transition-colors"
              >
                Batal
              </button>
              <button
                type="submit"
                disabled={saving}
                className="px-8 py-3 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold rounded-xl shadow-lg shadow-emerald-100 transition-all flex items-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {saving && <Loader2 className="w-4 h-4 animate-spin" />}
                <span>
                  {editingCertificate
                    ? "Update Sertifikat"
                    : "Simpan Sertifikat"}
                </span>
              </button>
            </div>
          </form>
        </Modal>
      )}

      {/* PDF Download Modal */}
      <PdfSignatureModal
        isOpen={isPdfModalOpen}
        onClose={() => setIsPdfModalOpen(false)}
        onDownload={handlePdfDownload}
        title="Pilih Format Sertifikat"
        variant="certificate"
      />
    </div>
  );
}
